import { readFileSync } from 'node:fs';
import path from 'node:path';

export const QA_WORKSPACE_ID = 'qa-regression-workspace';
export const QA_WORKSPACE_NAME = 'QA Regression Workspace';
export const QA_BASE_MONTH = '2026-06';
export const QA_ACCOUNTS = {
  owner: 'qa.owner@budget.test',
  editor: 'qa.editor@budget.test',
  member: 'qa.member@budget.test',
};
export const QA_COLLECTIONS = [
  'paymentAccounts',
  'paymentModes',
  'categories',
  'incomes',
  'templates',
  'expenses',
  'investments',
  'loanAccounts',
  'loanEvents',
  'loanReconciliations',
  'loanDocuments',
];

export function readQaFirebaseConfig(cwd = process.cwd()) {
  const environmentPath = path.join(cwd, 'src', 'environments', 'environment.qa.ts');
  const source = readFileSync(environmentPath, 'utf8');
  const block = source.match(/firebaseConfig\s*=\s*\{([\s\S]*?)\};/)?.[1];

  if (!block) {
    throw new Error(`Unable to read firebaseConfig from ${environmentPath}`);
  }

  return Object.fromEntries(
    [...block.matchAll(/^\s*([a-zA-Z0-9_]+):\s*'([^']*)'/gm)].map((match) => [match[1], match[2]]),
  );
}

export function buildQaSeedData() {
  const now = '2026-06-17T09:00:00.000Z';
  const archived = '2026-05-20T09:00:00.000Z';
  const owner = QA_ACCOUNTS.owner;
  const editor = QA_ACCOUNTS.editor;
  const member = QA_ACCOUNTS.member;

  const workspace = {
    id: QA_WORKSPACE_ID,
    name: QA_WORKSPACE_NAME,
    members: [
      { email: owner, displayName: 'QA Owner', role: 'owner', createdDate: now },
      { email: editor, displayName: 'QA Editor', role: 'editor', createdDate: now },
      { email: member, displayName: 'QA Member', role: 'editor', createdDate: now },
    ],
    createdDate: now,
    updatedDate: now,
  };

  const categories = [
    { id: 'cat-salary', name: 'Salary', monthlyBudget: 0, color: '#0f766e', type: 'Income' },
    { id: 'cat-bonus', name: 'Bonus', monthlyBudget: 0, color: '#1d4ed8', type: 'Income' },
    { id: 'cat-rent', name: 'Rent', monthlyBudget: 36000, color: '#7c3aed', type: 'Expenses' },
    {
      id: 'cat-groceries',
      name: 'Groceries',
      monthlyBudget: 18000,
      color: '#16a34a',
      type: 'Expenses',
    },
    {
      id: 'cat-utilities',
      name: 'Utilities',
      monthlyBudget: 9500,
      color: '#0f766e',
      type: 'Expenses',
    },
    { id: 'cat-travel', name: 'Travel', monthlyBudget: 12000, color: '#d97706', type: 'Expenses' },
    { id: 'cat-health', name: 'Health', monthlyBudget: 6000, color: '#be123c', type: 'Expenses' },
    {
      id: 'cat-investments',
      name: 'Investments',
      monthlyBudget: 30000,
      color: '#1d4ed8',
      type: 'Investments',
    },
    {
      id: 'category-loan-emi',
      name: 'Loan EMI',
      monthlyBudget: 0,
      color: '#4b5563',
      type: 'Expenses',
    },
  ];

  const paymentAccounts = [
    {
      id: 'acct-hdfc',
      name: 'HDFC Everyday QA',
      bankName: 'HDFC',
      lastFour: '4321',
      createdDate: now,
      memberEmail: owner,
    },
    {
      id: 'acct-sbi',
      name: 'SBI EMI QA',
      bankName: 'SBI',
      lastFour: '2468',
      createdDate: now,
      memberEmail: editor,
    },
    {
      id: 'acct-axis',
      name: 'Axis Backup QA',
      bankName: 'Axis',
      lastFour: '1357',
      createdDate: now,
      memberEmail: member,
    },
    {
      id: 'acct-archived',
      name: 'Old ICICI QA',
      bankName: 'ICICI',
      lastFour: '9090',
      createdDate: now,
      archivedDate: archived,
      memberEmail: owner,
    },
  ];

  const paymentModes = [
    {
      id: 'payment-mode-cash',
      type: 'cash',
      name: 'Cash',
      workspaceGlobal: true,
      createdDate: now,
    },
    {
      id: 'pm-upi-gpay',
      type: 'upi',
      provider: 'Google Pay',
      name: 'Google Pay QA',
      paymentAccountId: 'acct-hdfc',
      createdDate: now,
      memberEmail: owner,
    },
    {
      id: 'pm-wallet-paytm',
      type: 'upi',
      provider: 'Paytm',
      name: 'Paytm UPI QA',
      paymentAccountId: 'acct-axis',
      createdDate: now,
      memberEmail: member,
    },
    {
      id: 'pm-card-visa',
      type: 'credit-card',
      name: 'Visa Credit QA',
      cardType: 'visa',
      lastFour: '9002',
      paymentAccountId: 'acct-axis',
      createdDate: now,
      memberEmail: member,
    },
    {
      id: 'pm-card-rupay',
      type: 'debit-card',
      name: 'RuPay Debit QA',
      cardType: 'rupay',
      lastFour: '7711',
      paymentAccountId: 'acct-sbi',
      createdDate: now,
      memberEmail: editor,
    },
    {
      id: 'pm-netbanking-sbi',
      type: 'internet-banking',
      name: 'SBI NetBanking QA',
      bankName: 'Axis',
      paymentAccountId: 'acct-axis',
      createdDate: now,
      memberEmail: member,
    },
    {
      id: 'pm-archive-target',
      type: 'upi',
      provider: 'BHIM',
      name: 'Archive Target QA',
      paymentAccountId: 'acct-hdfc',
      createdDate: now,
      memberEmail: owner,
    },
    {
      id: 'pm-archived-upi',
      type: 'upi',
      provider: 'PhonePe',
      name: 'Old PhonePe QA',
      paymentAccountId: 'acct-archived',
      createdDate: now,
      archivedDate: archived,
      memberEmail: owner,
    },
  ];

  const incomes = [
    {
      id: 'income-salary-owner',
      source: 'Owner Salary',
      amount: 125000,
      cadence: 'monthly',
      categoryId: 'cat-salary',
      notes: 'QA monthly salary',
      startDate: '2026-01-01',
      memberEmail: owner,
    },
    {
      id: 'income-editor-salary',
      source: 'Editor Salary',
      amount: 85000,
      cadence: 'monthly',
      categoryId: 'cat-salary',
      notes: 'QA member salary',
      startDate: '2026-01-01',
      memberEmail: editor,
    },
    {
      id: 'income-one-time-bonus',
      source: 'June Bonus',
      amount: 35000,
      cadence: 'one-time',
      categoryId: 'cat-bonus',
      notes: 'QA one-time income',
      month: '2026-06',
      memberEmail: member,
    },
  ];

  const templates = [
    {
      id: 'tpl-rent-monthly',
      name: 'Monthly Rent',
      categoryId: 'cat-rent',
      amount: 32000,
      type: 'recurring',
      frequency: 'monthly',
      startDate: '2026-01-05',
      memberEmail: owner,
      paymentModeId: 'pm-upi-gpay',
      auditTrail: [
        {
          id: 'audit-rent-created',
          operation: 'created',
          recordedDate: '2026-01-05T08:00:00.000Z',
          name: 'Monthly Rent',
          categoryId: 'cat-rent',
          amount: 32000,
          frequency: 'monthly',
          startDate: '2026-01-05',
          memberEmail: owner,
          paymentModeId: 'pm-upi-gpay',
        },
      ],
    },
    {
      id: 'tpl-utilities-weekly',
      name: 'Weekly Utilities',
      categoryId: 'cat-utilities',
      amount: 650,
      type: 'recurring',
      frequency: 'weekly',
      startDate: '2026-06-03',
      memberEmail: editor,
      paymentModeId: 'pm-card-rupay',
    },
    {
      id: 'tpl-insurance-quarterly',
      name: 'Quarterly Insurance',
      categoryId: 'cat-health',
      amount: 7200,
      type: 'recurring',
      frequency: 'quarterly',
      startDate: '2026-03-10',
      memberEmail: owner,
      paymentModeId: 'pm-upi-gpay',
    },
    {
      id: 'tpl-school-half-yearly',
      name: 'Half-yearly School Fee',
      categoryId: 'cat-utilities',
      amount: 24000,
      type: 'recurring',
      frequency: 'half-yearly',
      startDate: '2026-06-12',
      memberEmail: member,
      paymentModeId: 'pm-wallet-paytm',
    },
    {
      id: 'tpl-annual-renewal',
      name: 'Annual Software Renewal',
      categoryId: 'cat-utilities',
      amount: 11800,
      type: 'recurring',
      frequency: 'annual',
      startDate: '2026-06-18',
      memberEmail: editor,
      paymentModeId: 'pm-card-rupay',
    },
    {
      id: 'tpl-ended-subscription',
      name: 'Ended Subscription',
      categoryId: 'cat-utilities',
      amount: 999,
      type: 'recurring',
      frequency: 'monthly',
      startDate: '2026-01-01',
      endDate: '2026-05-31',
      memberEmail: owner,
      paymentModeId: 'pm-upi-gpay',
    },
    {
      id: 'tpl-skipped-current',
      name: 'Skipped Current Month',
      categoryId: 'cat-travel',
      amount: 3000,
      type: 'recurring',
      frequency: 'monthly',
      startDate: '2026-01-20',
      skippedMonths: ['2026-06'],
      memberEmail: member,
      paymentModeId: 'pm-wallet-paytm',
    },
  ];

  const expenses = [
    {
      id: 'exp-2026-05-groceries',
      month: '2026-05',
      date: '2026-05-11',
      name: 'May Groceries',
      categoryId: 'cat-groceries',
      amount: 4100.5,
      type: 'one-time',
      note: 'Past month baseline',
      memberEmail: owner,
      paymentModeId: 'pm-upi-gpay',
    },
    {
      id: 'exp-2026-06-groceries',
      month: '2026-06',
      date: '2026-06-12',
      name: 'June Groceries',
      categoryId: 'cat-groceries',
      amount: 5820.75,
      type: 'one-time',
      note: 'Current month grocery run',
      memberEmail: owner,
      paymentModeId: 'pm-upi-gpay',
    },
    {
      id: 'exp-2026-06-medical',
      month: '2026-06',
      date: '2026-06-14',
      name: 'Clinic Visit',
      categoryId: 'cat-health',
      amount: 2100,
      type: 'one-time',
      note: 'Health expense',
      memberEmail: editor,
      paymentModeId: 'pm-card-rupay',
    },
    {
      id: 'exp-2026-06-travel-planned',
      month: '2026-06',
      date: '2026-06-28',
      name: 'Airport Cab Planned',
      categoryId: 'cat-travel',
      amount: 1450,
      type: 'one-time',
      note: 'Future planned expense',
      memberEmail: member,
      paymentModeId: 'pm-wallet-paytm',
    },
    {
      id: 'exp-2026-07-flight',
      month: '2026-07',
      date: '2026-07-03',
      name: 'July Flight',
      categoryId: 'cat-travel',
      amount: 18500,
      type: 'one-time',
      note: 'Future month planned travel',
      memberEmail: member,
      paymentModeId: 'pm-card-visa',
    },
  ];

  const investments = [
    {
      id: 'inv-index-sip',
      name: 'Index SIP',
      amount: 16000,
      categoryId: 'cat-investments',
      frequency: 'monthly',
      startDate: '2026-01-07',
      notes: 'Monthly SIP plan',
      memberEmail: owner,
      paymentModeId: 'pm-upi-gpay',
      auditTrail: [
        {
          id: 'audit-sip-created',
          operation: 'created',
          recordedDate: '2026-01-07T09:00:00.000Z',
          name: 'Index SIP',
          amount: 16000,
          categoryId: 'cat-investments',
          frequency: 'monthly',
          startDate: '2026-01-07',
          notes: 'Monthly SIP plan',
          memberEmail: owner,
          paymentModeId: 'pm-upi-gpay',
        },
      ],
    },
    {
      id: 'inv-weekly-gold',
      name: 'Weekly Gold',
      amount: 1200,
      categoryId: 'cat-investments',
      frequency: 'weekly',
      startDate: '2026-06-02',
      notes: 'Weekly investment schedule',
      memberEmail: editor,
      paymentModeId: 'pm-card-rupay',
    },
    {
      id: 'inv-annual-ppf',
      name: 'Annual PPF',
      amount: 50000,
      categoryId: 'cat-investments',
      frequency: 'annual',
      startDate: '2026-06-20',
      notes: 'Annual investment schedule',
      memberEmail: member,
      paymentModeId: 'pm-netbanking-sbi',
    },
    {
      id: 'inv-one-time-june',
      name: 'One-time Equity Buy',
      amount: 22000,
      categoryId: 'cat-investments',
      frequency: 'one-time',
      date: '2026-06-09',
      notes: 'One-time investment',
      memberEmail: owner,
      paymentModeId: 'pm-upi-gpay',
    },
  ];

  const loanAccounts = [
    {
      id: 'loan-home',
      schemaVersion: 2,
      lender: 'HDFC Home Loan',
      loanType: 'Home',
      contract: {
        sanctionedAmount: 5200000,
        disbursedAmount: 5200000,
        disbursementDate: '2024-06-01',
        firstEmiDate: '2024-07-15',
        originalTenureMonths: 144,
        contractualMaturityDate: '2036-06-15',
        initialEmi: 42500,
        initialAnnualRate: 8.45,
        interestType: 'fixed',
        interestCalculationMethod: 'monthly-reducing',
        dayCountConvention: 'actual-365',
        compoundingFrequency: 'monthly',
        postPrepaymentStrategy: 'keep-emi-reduce-tenure',
        roundingPolicy: {
          monetaryScale: 2,
          interestRounding: 'half-up',
          installmentRounding: 'half-up',
          finalInstallmentAdjustment: true,
        },
      },
      notes: 'Long-running home loan',
      memberEmail: owner,
      paymentModeId: 'pm-upi-gpay',
      historyCoverageStartDate: '2026-06-01',
    },
    {
      id: 'loan-personal',
      schemaVersion: 2,
      lender: 'SBI Personal Loan',
      loanType: 'Personal',
      contract: {
        sanctionedAmount: 250000,
        disbursedAmount: 250000,
        disbursementDate: '2025-11-20',
        firstEmiDate: '2025-12-05',
        originalTenureMonths: 9,
        contractualMaturityDate: '2026-08-05',
        initialEmi: 12500,
        initialAnnualRate: 11.2,
        interestType: 'fixed',
        interestCalculationMethod: 'monthly-reducing',
        dayCountConvention: 'actual-365',
        compoundingFrequency: 'monthly',
        postPrepaymentStrategy: 'keep-emi-reduce-tenure',
        roundingPolicy: {
          monetaryScale: 2,
          interestRounding: 'half-up',
          installmentRounding: 'half-up',
          finalInstallmentAdjustment: true,
        },
      },
      notes: 'Near closure loan',
      memberEmail: editor,
      paymentModeId: 'pm-card-rupay',
      historyCoverageStartDate: '2026-06-01',
    },
    {
      id: 'loan-vehicle',
      schemaVersion: 2,
      lender: 'Axis Vehicle Loan',
      loanType: 'Vehicle',
      contract: {
        sanctionedAmount: 880000,
        disbursedAmount: 880000,
        disbursementDate: '2026-07-01',
        firstEmiDate: '2026-07-10',
        originalTenureMonths: 49,
        contractualMaturityDate: '2030-07-10',
        initialEmi: 18500,
        initialAnnualRate: 9.1,
        interestType: 'fixed',
        interestCalculationMethod: 'monthly-reducing',
        dayCountConvention: 'actual-365',
        compoundingFrequency: 'monthly',
        postPrepaymentStrategy: 'keep-emi-reduce-tenure',
        roundingPolicy: {
          monetaryScale: 2,
          interestRounding: 'half-up',
          installmentRounding: 'half-up',
          finalInstallmentAdjustment: true,
        },
      },
      notes: 'Future-starting loan',
      memberEmail: member,
      paymentModeId: 'pm-card-visa',
    },
  ];

  const loanEvents = [
    {
      id: 'loan-home-opening-balance',
      loanId: 'loan-home',
      type: 'balance-anchor',
      effectiveDate: '2026-06-01',
      amount: 4380000,
      source: 'system',
      notes: 'QA opening balance',
      createdDate: '2026-06-01T09:00:00.000Z',
      memberEmail: owner,
    },
    {
      id: 'loan-personal-opening-balance',
      loanId: 'loan-personal',
      type: 'balance-anchor',
      effectiveDate: '2026-06-01',
      amount: 37500,
      source: 'system',
      notes: 'QA opening balance',
      createdDate: '2026-06-01T09:00:00.000Z',
      memberEmail: editor,
    },
  ];

  return {
    workspace,
    records: {
      paymentAccounts,
      paymentModes,
      categories,
      incomes,
      templates,
      expenses,
      investments,
      loanAccounts,
      loanEvents,
      loanReconciliations: [],
      loanDocuments: [],
    },
  };
}
