import type { LoanCalculationResult, LoanScheduleEntry } from './loan.models';

export interface LoanFinancialYearSummary {
  financialYear: string;
  openingBalance: number;
  principalRepaid: number;
  interestPaid: number;
  prepayments: number;
  charges: number;
  closingBalance: number;
  rows: LoanScheduleEntry[];
  disclaimer: string;
}

export function financialYearBounds(financialYearStart: number): {
  start: string;
  end: string;
  label: string;
} {
  return {
    start: `${financialYearStart}-04-01`,
    end: `${financialYearStart + 1}-03-31`,
    label: `FY ${financialYearStart}-${String(financialYearStart + 1).slice(-2)}`,
  };
}

export function buildFinancialYearSummary(
  calculation: LoanCalculationResult,
  financialYearStart: number,
): LoanFinancialYearSummary {
  const bounds = financialYearBounds(financialYearStart);
  const rows = calculation.schedule.filter(
    (row) => row.dueDate >= bounds.start && row.dueDate <= bounds.end && row.status !== 'future',
  );
  return {
    financialYear: bounds.label,
    openingBalance: rows[0]?.openingPrincipal ?? calculation.position.outstandingPrincipal,
    principalRepaid: rows.reduce((total, row) => total + row.principalComponent, 0),
    interestPaid: rows.reduce((total, row) => total + row.interestComponent, 0),
    prepayments: rows.reduce((total, row) => total + row.prepaymentAmount, 0),
    charges: rows.reduce((total, row) => total + row.charges, 0),
    closingBalance: rows.at(-1)?.closingPrincipal ?? calculation.position.outstandingPrincipal,
    rows,
    disclaimer:
      'Generated by Budget Battowski from recorded data; not an official lender certificate.',
  };
}
